### ISSUE TITLE
Sign up issue

### ISSUE THREAD

**Issue by JayHuangCa** [mokshajmera002/eElection#1]
hi,i its a great project and i would like to learn the structure here 
but i could not sign up 
it keep toasts"please enter all the details"
![屏幕截图 2023-12-20 143820](https://github.com/mokshajmera002/eElection/assets/149861104/32bcc80c-5d1e-4dbb-b008-99c2339948eb)

**Comment by mokshajmera002** [comment]
You will have to press the circular profile image to select your image then all the details will be filled.

**Comment by mokshajmera002** [comment]
You will have to press the circular profile image to select your image then all the details will be filled. This will be the same for all the activity which includes the circular profile image.
